In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from math import sqrt, exp, factorial
from scipy.stats import norm
from numpy.linalg import inv


In [2]:
C = np.array([[0.04, -0.04], [-0.04, 0.16]])
mu = np.array([[0.5], [0.6]])
# W = np.array([[0.5], [0.5]])
ones = np.ones((len(mu), 1))
W = ((ones.T @ inv(C)) / (ones.T @ inv(C) @ ones)).T
sqrt(W.T @ (C) @ W), W.T@mu


(0.13093073414159542, array([[0.52857143]]))

In [3]:
W.T*7

array([[5., 2.]])

In [4]:
num = 5 
rate = 0.08
face = 1000
coupon = 0.2
PV = sum([face*coupon/(1+rate)**i for i in range(1,num+1)])+face/(1+rate)**num
D = (sum([i for i in range(1,num+1)])*(face*coupon)+(face*num/(1+rate)**num))/PV
D

4.328853274833054

In [5]:
PV

1479.1252044493697

In [6]:
rhs = np.array([[10000/(1+0.08)**4.5, (10000*4.5)/(1+0.08)**4.5]]).T
lhs = np.array([[680.585 , 1479.125],[680.585*5 , 1479.125*3.83]])
ans = np.linalg.solve(lhs,rhs)
# lhs, rhs
# ans.T@lhs
ans.T, lhs

(array([[5.95113316, 2.04348929]]),
 array([[ 680.585  , 1479.125  ],
        [3402.925  , 5665.04875]]))

In [7]:
num = 3
periods = ["U" * i + "D" * (j - i) for j in range(num + 1) for i in range(j + 1)]
periods
u = 1.15
d = 1 - 0.03
r = 0.09
R = 1 + r
q = (R - d) / (u - d)
dic = {}


def C(Cu, Cd):
    global R, q
    return 1 /R * (q * Cu + (1 - q) * Cd)
lis= [70.357,59.3449,50.055]
lis= [58.9306,49.70668,41.9265]
for i,val in enumerate(lis):
    lis[i] = min(10,abs(val-55))
while len(lis) !=0:
    li = []
    for i in range(len(lis)-1):
        li.append(C(lis[i], lis[i + 1]))
    dic[len(lis)-1] = lis
    lis=li
dic

{2: [3.9305999999999983, 5.293320000000001, 10],
 1: [4.022788990825687, 6.295608562691128],
 0: [4.385683958514524]}

In [8]:
C(5.828596545371233,4.385683958514524)

4.906078608335472

# black scholes

In [23]:
K = 80
S = 87
T = 35/252
r = 5/100
vol = 0.2 
d1 = 1/(vol*sqrt(T))*(np.log(S/K)+(r+vol**2/2)*(T))

d2 = 1/(vol*sqrt(T))*(np.log(S/K)+(r-vol**2/2)*(T))
print('put: '+ str(-norm.cdf(-d1)*S+norm.cdf(-d2)*K*exp(-r*(T))))
K = 90 
d1 = 1/(vol*sqrt(T))*(np.log(S/K)+(r+vol**2/2)*(T))
d2 = 1/(vol*sqrt(T))*(np.log(S/K)+(r-vol**2/2)*(T))
'call: ',str(norm.cdf(d1)*S-norm.cdf(d2)*K*exp(-r*(T)))

put: 0.3344657549181722


('call: ', '1.6026620198534722')

In [24]:
1.6026620198534722+0.3344657549181722

1.9371277747716444

In [37]:
C = np.array([[ 0.4,0.2],[0.2,0.3]])
mu = np.array([[0.4,0.3]]).T
ones = np.ones((len(mu),1))
r = 5/100

W= ((ones.T@inv(C))/(ones.T@inv(C)@ones)).T
W= (((mu-ones*r).T@inv(C))/((mu-ones*r).T@inv(C)@ones)).T
sigma2 = W.T@C@W
mu = W.T@mu
mu, (sigma2), W

(array([[0.36470588]]),
 array([[0.29619377]]),
 array([[0.64705882],
        [0.35294118]]))

In [ ]:
r = 5.02/100
S = 30 
K = 32 
v = 5/100
vol = 2/100
R = r+1 
q = (R-d)/(u-d)